### ISSUE TITLE
strings.map is not a function at getTemplate (lib/template.js:24:18)

### ISSUE THREAD

**Issue by nkbt** [bholloway/react-i18n-interpolation#7]
```sh
4/4/2017, 13:22:08
  error: 'TypeError'
  message: 'strings.map is not a function'
  stack: 
     '    at getTemplate (/Users/nkbt/mh/reef/packages/i18n/node_modules/react-i18n-interpolation/lib/template.js:24:18)'
     '    at /Users/nkbt/mh/reef/packages/i18n/node_modules/react-i18n-interpolation/lib/index.js:60:43'
     '    at GettextContent (/Users/nkbt/mh/reef/packages/react/Gettext/index.js:10:54)'
     '    at /Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16'
     '    at measureLifeCyclePerf (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)'
     '    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:305:14)'
     '    at ReactCompositeComponentWrapper._constructComponent (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:280:21)'
     '    at ReactCompositeComponentWrapper.mountComponent (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:188:21)'
     '    at Object.mountComponent (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactReconciler.js:46:35)'
     '    at ReactCompositeComponentWrapper.performInitialMount (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)'
     '    at ReactCompositeComponentWrapper.mountComponent (/Users/nkbt/mh/reef/packages/user-ui/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)'
 ```

**Comment by nkbt** [comment]
Most likely was cause by old component that run `ngettext(sing, plural, num, {subs})`

Obviously incorrect API, but still input should be probably better validated.

**Comment by bholloway** [comment]
Per #15 this error case will be caught because it does not match `ngettext(integer)` invocation.

**Comment by nkbt** [comment]
Same problem when doing
```
const x = gettext('whatever')
```

```
TypeError: strings.map is not a function
    at getTemplate (./node_modules/react-i18n-interpolation/lib/template.js:24:18)
    at ./node_modules/react-i18n-interpolation/lib/index.js:62:43
```
